allowBuilds:
  node-pty: true
  esbuild: true
  better-sqlite3: true
  tesseract.js: false

overrides:
  nf3: "0.3.17"
  "@assistant-ui/tap": "^0.5.14"
  "@assistant-ui/store": ">=0.2.9 <0.2.14"
  vite: 'catalog:'
  vitest: 'catalog:'

minimumReleaseAgeExclude:
  - typescript-7
  - typescript
  - fast-xml-parser
  - "@sentry/*"
  - "@typescript/*"
  - "@modelcontextprotocol/server"
  - "@modelcontextprotocol/node"
  - "@modelcontextprotocol/core"
  - "@modelcontextprotocol/client"
  - '@agent-native/core@0.133.1'

patchedDependencies:
  '@agent-native/core@0.133.1': patches/@agent-native__core@0.133.1.patch
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.13
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.13
  vite-plus: 0.1.13
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
